### ISSUE TITLE
image preview

### ISSUE THREAD

**Issue by sassanh** [panickbr/neovim-ranger#1]
Thanks for this extension, it solves common problems with `neovim` though it doesn't show image previews (I'm testing it in ITerm) it'd be great if you could introduce a workaround for image previews too.

**Comment by panickbr** [comment]
Hey, thanks for reaching out. I had completely forgotten I put this up on github.

About your issue, this is out of my scope. It's not a problem with this extension, since the only thing it does is spawn a neovim terminal and launch the ranger app.

The problem lies on neovim's terminal emulation itself. You can read more on this here:
- neovim/neovim#4502
- neovim/neovim#4056
- neovim/neovim#4349

**Comment by sassanh** [comment]
@panickbr thanks for info.
